version: "2"
services:
  g1_mariadb:
    image: 'mariadb:10.1'
    container_name: g1_mariadb
    environment:
      #MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: splc2017
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes: 
      - ./db_dump:/docker-entrypoint-initdb.d
      - db_data_g1_mariadb:/var/lib/mysql
  g1_wordpress:
    links:
      - g1_mariadb:mysql
    image: wordpress
    container_name: g1_wordpress
    working_dir: /var/www/html
    volumes:
      - ./wp-content/:/var/www/html/wp-content
    environment:
      VIRTUAL_HOST: g1wordpress.egc.duckdns.org
      LETSENCRYPT_HOST: g1wordpress.egc.duckdns.org
      LETSENCRYPT_EMAIL: migbancar@alum.us.es
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_HOST: g1_mariadb:3306
      WORDPRESS_DB_NAME: splc2017

#Volumen para los datos del mysql, para que se guarden fuera del contenedor
volumes:
  db_data_g1_mariadb:

networks:
  default:
    external:
      name: proxy_net